Реализация Бизнес логики
Resalner/JavaPractice pull request #14
Opened 2024-07-11 10:13 UTC by Kuchikamba

2024-07-12 07:30 UTC, dulfinne commented on src/main/java/com/github/resalner/javapractice/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
EntityNotFoundException

2024-07-12 13:34 UTC, Maxanko requested changes

2024-07-12 13:34 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressServiceImpl.java
> +public class AddressServiceImpl{
```suggestion
public class AddressServiceImpl {
```

2024-07-12 13:34 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressServiceImpl.java
> +  }
Не создавай конструктор сам, используй `@RequiredArgsConstructor` из Lombok

2024-07-12 13:34 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressServiceImpl.java
> +  }
Подтяни сюда изменения из ветки master, чтобы поменялись названия полей, а то они тут ещё старые

2024-07-12 13:34 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressServiceImpl.java
> +    return addressRepository.findById(id).orElseThrow(()->EntityNotFoundException("не найден адрес с id = "+id));
orElseThrow пиши с новой строки

2024-07-12 13:34 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressServiceImpl.java
> +    addressRepository.save(ad);
После блока if лучше вставлять пустую строку, это увеличивает читаемость кода

2024-07-12 13:34 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/CategoryServiceImpl.java
> +
Пустые строки лишние

2024-07-12 13:34 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/CategoryServiceImpl.java
> +  @Autowired
Когда мы внедряем через конструктор, аннотация `@Autowired` не нужна

2024-07-12 13:34 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/CategoryServiceImpl.java
> +  }
Не прописывай конструктор самостоятельно, используй Lombok

2024-07-12 13:34 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/CategoryServiceImpl.java
> +  }
Не забывай прожимать ctrl + alt + L , он автоматом расставит нужные пробелы
```suggestion
    return categoryRepository.findById(id)
    .orElseThrow(() -> EntityNotFoundException("не найдена категория с id = " + id));
  }
```

2024-07-12 13:34 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/CategoryServiceImpl.java
> +    category.setName(categoryRequest.name());
Лучше конечно не создавать сущности  самостоятельно, а использовать библиотеки типо Mapstruckt
Посмотри про неё и используй

2024-07-12 13:37 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressServiceImpl.java
> +    addressRepository.save(ad);
И хорошей практикой для повышения читаемости кода является перенос && на новую строку
То есть писать вместо:
if(Objects.nonNull(addressRequest.street()) && !"".equals(addressRequest.street())) {
Вот так:
if(Objects.nonNull(addressRequest.street()) 
    && !"".equals(addressRequest.street())) {

2024-07-16 07:23 UTC, Maxanko requested changes

2024-07-16 07:23 UTC, Maxanko commented on pom.xml
> +            <version>1.18.30</version>
Версии выноси в тег properties

2024-07-16 07:23 UTC, Maxanko commented on pom.xml
> +            <version>1.6.0.Beta1</version>
Версии выноси в тег properties

2024-07-16 07:23 UTC, Maxanko commented on pom.xml
> +                <version>3.11.0</version>
Версии выноси в тег properties

2024-07-16 07:23 UTC, Maxanko commented on pom.xml
> +                            <version>1.6.0.Beta1</version>
Версии выноси в тег properties

2024-07-16 07:23 UTC, Maxanko commented on pom.xml
> +                <version>3.6.3</version>
Версии выноси в тег properties

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/map/AddressMapper.java
> +    AddressMapper INSTANCE = Mappers.getMapper(AddressMapper.class);
Это не обязательно, когда пишем MappingConstants.ComponentModel.SPRING, маппер помещается в контекст спринга сам, и тогда нет нужды обращаться к нему через статическое поле

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/map/AddressMapper.java
> +    @Mapping(target = "apartamentNumber", source = "apartamentNumber")
Когда названия полей совпадают, мы можем не прописывать их в Mapping

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/map/CategoryMapper.java
Те же замечания, что и для AddressMapper

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/map/OrderItemMapper.java
Те же замечания, что и для AddressMapper

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/map/OrderMapper.java
Те же замечания, что и для AddressMapper

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/map/ProductMapper.java
Те же замечания, что и для AddressMapper

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/map/UserInfoMapper.java
Те же замечания, что и для AddressMapper

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/map/UserMapper.java
Те же замечания, что и для AddressMapper

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressServiceImpl.java
> +
```suggestion
```

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressServiceImpl.java
> +
```suggestion
```

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressServiceImpl.java
> +
```suggestion
```

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressServiceImpl.java
> +
```suggestion
```

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressService.java
> +    void saveAddress(AddressRequest addressRequest);
Он не должен принимать  AddressRequest
Метод должен принимать объект класса Address

Сервисы должны работать только с классами внутреннего представления(Address, Category, OrderItem и тд, а все ...Request должны оставаться на уровне контроллеров)

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressService.java
> +    Address updateAddress(long id, AddressRequest addressRequest);
Метод должен принимать объект класса Address

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressService.java
> +
```suggestion
```

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/CategoryService.java
> +    void saveCategory(CategoryRequest categoryRequest);
Сервисы должны работать только с классами внутреннего представления(Address, Category, OrderItem и тд, а все ...Request должны оставаться на уровне контроллеров)

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/CategoryServiceImpl.java
> +
```suggestion
```

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/OrderItemService.java
> +    void saveOrderItem(OrderItemRequest orderItemRequest);
Сервисы должны работать только с классами внутреннего представления(Address, Category, OrderItem и тд, а все ...Request должны оставаться на уровне контроллеров)

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/OrderItemServiceImpl.java
> +        orderItem.setPrice(orderItemRequest.price());
Вот это должно происходить в контроллере с использованием мапперов(не зря же вы их прописали)

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/OrderItemServiceImpl.java
> +
```suggestion
```

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/OrderItemServiceImpl.java
> +
```suggestion
```

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/OrderItemServiceImpl.java
> +    }
Что-то вы забыли тут return прописать

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/OrderServiceImpl.java
> +    public void saveOrder(OrderRequest orderRequest) {
Сервисы должны работать только с классами внутреннего представления(Address, Category, OrderItem и тд, а все ...Request должны оставаться на уровне контроллеров)

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/OrderServiceImpl.java
> +        order.setComments(orderRequest.comments());
В контроллеры этот код

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/OrderServiceImpl.java
> +    }
Код не должен был  скомпилироваться, у вас тут return нет, а в объявлении метода указано, что он возвращает Order

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/ProductServiceImpl.java
> +        productRepository.save(pr);
Добавь return

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/CategoryServiceImpl.java
> +        categoryRepository.save(category);
Нет return

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressServiceImpl.java
> +        addressRepository.save(ad);
добавь return

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/UserInfoServiceImpl.java
> +    public void saveUserInfo(UserInfoRequest userInfoRequest) {
Сервисы должны работать только с классами внутреннего представления(Address, Category, OrderItem и тд, а все ...Request должны оставаться на уровне контроллеров)

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/UserInfoServiceImpl.java
> +        userInfoRepository.save(ui);
куегкт

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/UserServiceImpl.java
> +    public void saveUser(UserRequest userRequest) {
Сервисы должны работать только с классами внутреннего представления(Address, Category, OrderItem и тд, а все ...Request должны оставаться на уровне контроллеров)

2024-07-16 07:23 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/UserServiceImpl.java
> +        userRepository.save(us);
return

2024-07-16 08:16 UTC, Maxanko requested changes

2024-07-16 08:16 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressServiceImpl.java
> +        mapper.map(addressRequest, address);
Сохрани адрес

2024-07-18 07:21 UTC, Maxanko requested changes

2024-07-18 07:21 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressServiceImpl.java
> +        return address;
Возвращай сохранённый объект, а не тот, что пришёл в параметрах метода

2024-07-18 07:21 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/CategoryServiceImpl.java
> +    }
А почему здесь ничего не возвращаешь?

2024-07-18 07:21 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/OrderServiceImpl.java
> +        Order or = orderRepository.findById(id)
or не лучшее название, order

2024-07-18 07:21 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/OrderServiceImpl.java
> +    public Order updateOrder(long id, Order order) {
и тут тогда не order, а orderForUpdate

2024-07-18 07:21 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/ProductServiceImpl.java
> +        Product pr = productRepository.findById(id)
Называй полностью переменные, 2-е буквы не лучшее решение

2024-07-18 07:21 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/UserInfoServiceImpl.java
> +        UserInfo ui = userInfoRepository.findById(id)
ui обычно значит совсем другое, плохой нейминг
Назови userInfo, а параметр метода переименуй

2024-07-18 07:21 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/UserServiceImpl.java
> +        User us = userRepository.findById(id)
Опять же, нейминг не лучший, переименуй

2024-07-18 07:21 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/OrderService.java
> +    void saveOrder(OrderRequest orderRequest);
а почему он принимает Request?

2024-07-18 07:21 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/OrderServiceImpl.java
> +    }
Каждый метод интерфейса, который ты реализовала в классе, должен быть помечен аннотацией `@Override`

2024-07-19 13:47 UTC, Maxanko requested changes

2024-07-19 13:47 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/AddressServiceImpl.java
> +        return address;
Возвращай сохранённый адрес

2024-07-19 13:47 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/CategoryServiceImpl.java
> +        return category;
Возвращай сохранённую категорию

2024-07-19 13:47 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/OrderItemServiceImpl.java
> +public class OrderItemServiceImpl implement OrderItemService {
implements, а не implement

2024-07-19 13:47 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/OrderItemServiceImpl.java
> +        return orderItem;
```suggestion
        return orderItemRepository.save(orderItem);
```

2024-07-19 13:47 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/OrderServiceImpl.java
> +public class OrderServiceImpl implement OrderService {
```suggestion
public class OrderServiceImpl implements OrderService {
```

2024-07-19 13:47 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/OrderServiceImpl.java
> +        return order;
```suggestion
        
        return orderRepository.save(order);
```

2024-07-19 13:47 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/ProductServiceImpl.java
> +public class ProductServiceImpl implement ProductService {
```suggestion
public class ProductServiceImpl implements ProductService {
```

2024-07-19 13:47 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/ProductServiceImpl.java
> +        return product;
```suggestion
        
        return productRepository.save(product);;
```

2024-07-19 13:47 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/UserInfoServiceImpl.java
> +        return userInfo;
```suggestion
        
        return userInfoRepository.save(userInfo);
```

2024-07-19 13:47 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/UserInfoServiceImpl.java
> +public class UserInfoServiceImpl implement UserInfoService {
```suggestion
public class UserInfoServiceImpl implements UserInfoService {
```

2024-07-19 13:47 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/UserServiceImpl.java
> +public class UserServiceImpl implement UserService {
```suggestion
public class UserServiceImpl implements UserService {
```

2024-07-19 13:47 UTC, Maxanko commented on src/main/java/com/github/resalner/javapractice/service/UserServiceImpl.java
> +        return user;
```suggestion
        
        return userRepository.save(user);
```

2024-07-22 09:40 UTC, Maxanko approved these changes

2024-07-25 12:35 UTC, merged